"""Conservative, deterministic answers from annual statement rows.

This is a supported-layout parser, not a universal PDF table extractor or a
validator of arbitrary model prose. Unknown layouts/scopes stay unchecked.
Money uses Decimal throughout; every rendered value retains its original cell.
"""
from decimal import Decimal, localcontext
import re

VERSION = 1
SCALES = {"units": Decimal(1), "thousands": Decimal(1000),
          "millions": Decimal(1000000), "billions": Decimal(1000000000)}
# Exact labels prevent a nearby subtotal or a combined liabilities/equity row
# from substituting for the requested metric.
ALIASES = {
    "revenue": ("total net sales", "total revenues", "total revenue", "net operating revenues", "net sales", "revenues", "revenue"),
    "operating_income": ("operating income", "income from operations", "operating profit"),
    "net_income": ("net income", "net earnings", "net income (loss)"),
    "research_and_development": ("research and development", "research and development expense", "research and development expenses", "r&d expense"),
    "services_revenue": ("services net sales", "services revenue", "services revenues"),
    "cash_and_equivalents": ("cash and cash equivalents",),
    "current_assets": ("total current assets",),
    "current_liabilities": ("total current liabilities",),
    "total_assets": ("total assets",),
    "total_liabilities": ("total liabilities",),
    "shareholders_equity": ("total shareholders equity", "shareholders equity", "total stockholders equity", "stockholders equity"),
    "operating_cash_flow": ("cash generated by operating activities", "net cash provided by operating activities", "net cash from operating activities", "net cash provided by (used in) operating activities", "net cash from operations", "operating cash flow"),
    "capital_expenditure": ("payments for acquisition of property, plant and equipment", "purchases of property and equipment", "purchases of property, plant and equipment", "additions to property and equipment", "capital expenditures", "capital expenditure", "capex"),
}
LABELS = {key: values[0].capitalize() for key, values in ALIASES.items()}
LABELS.update(revenue="Revenue", shareholders_equity="Shareholders’ equity",
              capital_expenditure="Payments for property, plant and equipment",
              current_assets="Total current assets",
              current_liabilities="Total current liabilities")
BALANCE_METRICS = {"cash_and_equivalents", "current_assets", "current_liabilities",
                   "total_assets", "total_liabilities", "shareholders_equity"}
CASH_METRICS = {"operating_cash_flow", "capital_expenditure"}
SYMBOL_CURRENCIES = {"$": {"USD", "CAD", "AUD", "HKD", "SGD"},
                     "€": {"EUR"}, "£": {"GBP"}, "¥": {"JPY", "CNY", "RMB"}}
# Issuer HTML (e.g. Microsoft) may use "Income Statements" / "Cash Flows Statements"
# or a "Financial Statements:" prefix. Segment/adjusted variants stay rejected via
# UNSUPPORTED_TABLE. Keep the pattern line-bounded so prose mentions do not match.
STATEMENT = re.compile(
    r"^\s*(?:financial statements:\s*)?(?:consolidated\s+)?"
    r"(?:statements? of (?:operations|income|earnings|cash flows?|comprehensive income|"
    r"shareholders.? equity|stockholders.? equity)|income statements?|"
    r"cash flows? statements?|balance sheets?)\s*$",
    re.I | re.M,
)
YEAR = re.compile(r"\b(?:19|20)\d{2}\b")
NUMBER = r"(?:\d{1,3}(?:,\d{3})+|\d+)(?:\.\d+)?"
CELL = re.compile(rf"(?:\(\s*{NUMBER}\s*\)|[-−]?{NUMBER}|—|–|-|N/A)", re.I)
CURRENCIES = re.compile(r"\b(?:USD|EUR|GBP|CAD|AUD|JPY|CNY|RMB|INR|CHF|HKD|SGD)\b", re.I)
UNSUPPORTED_TABLE = re.compile(r"\b(?:forecast\w*|projected|projection\w*|pro[ -]?forma|adjusted|non[ -]?gaap|segment\w*|geographic\w*|supplemental)\b", re.I)


def normalized(text):
    return re.sub(r"\s+", " ", text.lower().replace("’", "'").replace("'", "")).strip().rstrip(":")


def _row(line):
    """Return label/cells only if the entire numeric suffix is well formed."""
    match = re.match(r"^(.+?[A-Za-z):])\s+((?:[$€£¥]\s*)?(?:[-−]?\d|\(|—|–|N/A|-(?:\s|$)).*)$", line.strip())
    if not match:
        return None
    suffix = re.sub(r"[$€£¥]", "", match[2]).strip()
    cells, end = [], 0
    for cell in CELL.finditer(suffix):
        if suffix[end:cell.start()].strip() or (end and cell.start() == end):
            return None
        cells.append(cell[0])
        end = cell.end()
    if not cells or suffix[end:].strip():
        return None
    return match[1], cells


def _units(header, source):
    # Only the leading monetary scale applies. Share counts and per-share
    # exceptions never set the money scale, and EPS is not a supported metric.
    unit_lines = [line for line in header.splitlines()
                  if re.search(r"\b(?:thousands|millions|billions|USD|EUR|GBP|CAD|AUD|JPY|CNY|RMB|INR|CHF|HKD|SGD|dollars|euros)\b", line, re.I)]
    if len(unit_lines) != 1:
        return None
    leading = re.split(r"\bexcept\b", unit_lines[0], maxsplit=1, flags=re.I)[0]
    scales = re.findall(r"\b(thousands|millions|billions)\b", leading.lower())
    if len(set(scales)) > 1:
        return None
    codes = set(code.upper() for code in CURRENCIES.findall(leading))
    if re.search(r"\b(?:U\.?S\.?|United States) dollars\b", leading, re.I):
        codes.add("USD")
    if re.search(r"\beuros\b", leading, re.I):
        codes.add("EUR")
    if len(codes) > 1:
        return None
    currency = next(iter(codes), source.get("currency"))
    # A bare '$' does not distinguish US, Canadian or Australian dollars.
    if not scales and not codes:
        return None
    return (scales[0] if scales else "units"), currency, unit_lines[0]


def table_facts(sources):
    """Extract supported cells, preserving duplicates for conflict detection."""
    facts = []
    for source in sources:
        text = source.get("text", "")
        starts = list(STATEMENT.finditer(text))
        for index, match in enumerate(starts):
            region = text[match.end():starts[index + 1].start() if index + 1 < len(starts) else len(text)]
            lines = region.splitlines()
            first_row = next((i for i, line in enumerate(lines) if _row(line)), None)
            if first_row is None:
                continue
            header = match[0].strip() + "\n" + "\n".join(lines[:first_row])
            balance = "balance sheet" in match[0].lower()
            cash = "cash flow" in match[0].lower()
            if UNSUPPORTED_TABLE.search(header):
                continue
            # A fiscal year label alone cannot establish an annual flow period.
            if re.search(r"\b(?:months?|quarters?)\b", header, re.I):
                continue
            if not balance and not re.search(r"\b(?:years? ended|annual)\b", header, re.I):
                continue
            years = [int(year) for year in YEAR.findall(header)]
            if not 1 <= len(years) <= 3 or len(years) != len(set(years)):
                continue
            units = _units(header, source)
            if units is None:
                continue
            scale, currency, unit_header = units
            group = next((normalized(line) for line in reversed(lines[:first_row])
                          if line.strip().endswith(":")), None)
            pending = []
            for line in lines[first_row:]:
                # Never let a later table/footnote inherit this table's header.
                if UNSUPPORTED_TABLE.search(line):
                    break
                if re.search(r"(?:see accompanying|notes to|form 10-k\s*\||\b(?:in|USD|EUR|GBP|CAD|AUD) (?:thousands|millions|billions)\b|\b(?:quarterly|supplemental|months? ended|years? ended)\b)", line, re.I):
                    break
                if line.strip().endswith(":"):
                    group, pending = normalized(line), []
                    continue
                row = _row(line)
                raw = line
                if row and pending:
                    # Support a wrapped label only when its combined text is
                    # exactly a known alias; a prior row never joins this one.
                    combined = _row(" ".join(pending + [line.strip()]))
                    if combined and any(normalized(combined[0]) in aliases for aliases in ALIASES.values()):
                        row, raw = combined, "\n".join(pending + [line])
                if not row:
                    pending = (pending + [line.strip()])[-2:] if line.strip() else []
                    continue
                pending = []
                label, cells = row
                symbols = {symbol for symbol in SYMBOL_CURRENCIES if symbol in raw}
                if len(symbols) > 1 or (currency and any(currency not in SYMBOL_CURRENCIES[s] for s in symbols)):
                    continue  # a row-level currency conflict is never erased
                metric = next((key for key, aliases in ALIASES.items() if normalized(label) in aliases), None)
                if normalized(label) == "services" and group in ("net sales", "revenue", "revenues"):
                    metric = "services_revenue"
                if metric is None or len(cells) != len(years):
                    continue
                if metric in BALANCE_METRICS and not balance:
                    continue
                if metric in CASH_METRICS and not cash:
                    continue
                if metric not in BALANCE_METRICS | CASH_METRICS | {"net_income"} and (balance or cash):
                    continue
                for year, cell in zip(years, cells):
                    if cell in ("—", "–", "-") or cell.upper() == "N/A":
                        continue
                    signed = cell.replace(",", "").replace("−", "-").replace(" ", "")
                    value = Decimal(signed.strip("()")) * (-1 if signed.startswith("(") else 1)
                    annual_balance = bool(re.search(r"\b(?:years? ended|annual)\b", header, re.I))
                    # Known sample fiscal endpoints are explicit provenance;
                    # arbitrary uploaded balance sheets get no such assumption.
                    endpoints = source.get("fiscal_year_ends", {})
                    endpoint = endpoints.get(str(year))
                    if endpoint and normalized(endpoint) in normalized(header):
                        annual_balance = True
                    facts.append({"metric": metric, "year": year,
                                  "value": str(value * SCALES[scale]), "currency": currency,
                                  "scale": scale, "raw_value": cell, "source_id": source["id"],
                                  "file": source.get("file", ""), "page": source.get("page"),
                                  "row": raw.strip(), "header": header, "unit_header": unit_header,
                                  "period_kind": ("year_end" if annual_balance else "as_of") if balance else "annual",
                                  "table_id": f"{source['id']}:{index}"})
    return facts


def _request(question, sources):
    """Recognize a small grammar; leftover scope words require normal analysis.

    We intentionally do not strip arbitrary company names or qualifiers. A
    request for Europe, adjusted/organic figures, forecasts or explanations
    must not silently become a consolidated reported-number answer.
    """
    query = normalized(question)
    if re.search(r"\bas of\b", query):
        return None  # availability cutoffs require a different evidence contract
    identities = {tuple(sorted(normalized(n) for n in s.get("entity_names", []))) for s in sources}
    if len(identities) > 1:
        return None  # do not transfer identity between retrieved sources
    years = [int(year) for year in re.findall(r"\b(?:fy)?((?:19|20)\d{2})\b", query)]
    if not 1 <= len(years) <= 2 or len(set(years)) != len(years):
        return None
    formula = None
    if "operating margin" in query:
        formula, query = "operating_margin", query.replace("operating margin", " ")
        metrics = ["operating_income", "revenue"]
    elif "net margin" in query:
        formula, query = "net_margin", query.replace("net margin", " ")
        metrics = ["net_income", "revenue"]
    elif "return on equity" in query or re.search(r"\broe\b", query):
        formula, query = "roe", re.sub(r"\breturn on equity\b|\broe\b", " ", query)
        metrics = ["net_income", "shareholders_equity"]
    elif "current ratio" in query:
        formula, query = "current_ratio", query.replace("current ratio", " ")
        metrics = ["current_assets", "current_liabilities"]
    elif "free cash flow" in query or re.search(r"\bfcf\b", query):
        formula, query = "free_cash_flow", re.sub(r"\bfree cash flow\b|\bfcf\b", " ", query)
        metrics = ["operating_cash_flow", "capital_expenditure"]
    elif "growth" in query:
        formula, query = "metric_growth", query.replace("growth", " ")
        metrics = []
    else:
        metrics = []
    # Longest match first prevents 'services net sales' becoming total revenue.
    choices = sorted(((alias, metric) for metric, aliases in ALIASES.items() for alias in aliases), key=lambda item: len(item[0]), reverse=True)
    for alias, metric in choices:
        pattern = r"(?<!\w)" + re.escape(alias) + r"(?!\w)"
        if re.search(pattern, query):
            metrics.append(metric)
            query = re.sub(pattern, " ", query)
    metrics = list(dict.fromkeys(metrics))
    if not metrics or len(metrics) > 3:
        return None
    for name in {n for s in sources for n in s.get("entity_names", [])}:
        query = re.sub(r"\b" + re.escape(normalized(name)) + r"(?:s)?\b", " ", query)
    requested_codes = set(code.upper() for code in CURRENCIES.findall(query))
    if len(requested_codes) > 1:
        return None
    query = CURRENCIES.sub(" ", query)
    query = re.sub(r"\b(?:fy)?(?:19|20)\d{2}\b", " ", query)
    query = re.sub(r"[^a-z]+", " ", query)
    allowed = set("what was were is are how much did the this company companys reported report annual fiscal year years end at in for from to and of amount amounts give show me please calculate compute cite statement filing document usd million millions billion billions thousand thousands dollars outflow magnitude on during with sources source percentage percent free cash flow flows fcf net margin margins return equity roe current ratio assets liabilities growth".split())
    if set(query.split()) - allowed:
        return None
    if formula in ("operating_margin", "net_margin", "free_cash_flow", "roe", "current_ratio") and len(metrics) != 2:
        return None
    if formula == "metric_growth" and (len(years) != 2 or years[1] <= years[0] or len(metrics) != 1):
        return None
    return metrics, years, formula, next(iter(requested_codes), None)


def _unavailable(reason):
    return {"text": "I couldn’t check this figure against the retrieved statement rows. " + reason,
            "warnings": [], "verification": {"version": VERSION, "status": "unavailable",
            "scope": "Supported annual statement figures only", "reason": reason, "facts": [], "calculations": []}}


def _number(value):
    value = format(value, ",f")
    return value.rstrip("0").rstrip(".") if "." in value else value


def _money(value, currency, scale="millions"):
    prefix = "$" if currency == "USD" else f"{currency} "
    unit = "" if scale == "units" else " " + scale.rstrip("s")
    return prefix + _number(value / SCALES[scale]) + unit


def quantitative_answer(question, sources):
    """Return deterministic output, an explicit abstention, or None for prose."""
    request = _request(question, sources)
    if request is None or not any(STATEMENT.search(s.get("text", "")) for s in sources):
        return None
    metrics, years, formula, requested_currency = request
    facts = table_facts(sources)
    selected = []
    for metric in metrics:
        for year in years:
            matches = [f for f in facts if f["metric"] == metric and f["year"] == year]
            if not matches:
                return _unavailable(f"A complete {year} {LABELS[metric].lower()} row with an explicit period and scale is missing. Open the sources to inspect the table.")
            # Margin/ROE formulas need the income-statement net income row, not a
            # cash-flow restatement, so the income inputs stay on one table.
            if formula in ("operating_margin", "net_margin", "roe") and metric == "net_income":
                income_rows = [f for f in matches if "cash flow" not in f["header"].lower()]
                if income_rows:
                    matches = income_rows
            if formula == "roe" and metric == "shareholders_equity":
                year_end = [f for f in matches if f["period_kind"] == "year_end"]
                if year_end:
                    matches = year_end
            if formula == "current_ratio" and metric in ("current_assets", "current_liabilities"):
                year_end = [f for f in matches if f["period_kind"] == "year_end"]
                if year_end:
                    matches = year_end
            if formula in ("operating_margin", "net_margin") and metric != "net_income":
                income_rows = [f for f in matches if "cash flow" not in f["header"].lower()]
                if income_rows:
                    matches = income_rows
            values = {(Decimal(f["value"]), f["currency"], f["period_kind"], f["file"]) for f in matches}
            if len(values) != 1:
                return _unavailable(f"The retrieved rows disagree about {year} {LABELS[metric].lower()}. Resolve the conflicting statements before using this figure.")
            fact = matches[0]
            if fact["period_kind"] == "as_of" and re.search(r"\byear[ -]end\b", question, re.I):
                return _unavailable("The balance-sheet dates do not establish the company's fiscal year end. The header must identify that reporting period.")
            if formula == "roe" and metric == "shareholders_equity" and fact["period_kind"] != "year_end":
                return _unavailable("Return on equity needs shareholders’ equity at fiscal year end, not an interim balance.")
            if formula == "current_ratio" and fact["period_kind"] != "year_end":
                return _unavailable("Current ratio needs year-end current assets and current liabilities, not interim balances.")
            if not fact["currency"] or (requested_currency and fact["currency"] != requested_currency):
                return _unavailable("The statement does not establish the requested currency. A dollar symbol alone is not enough to identify USD; no currency conversion was performed.")
            selected.append(fact)
    verification = {"version": VERSION, "status": "verified", "method": "deterministic_statement_cells",
                    "scope": "Displayed figures and formulas checked against supported statement rows; not a validation of the filing itself.",
                    "facts": selected, "calculations": []}
    lines = []
    if formula:
        currencies = {f["currency"] for f in selected}
        if len(currencies) != 1:
            return _unavailable("The calculation needs compatible inputs from the same currency.")
        # ROE intentionally joins an income statement with a year-end balance sheet.
        if formula != "roe" and len({f["table_id"] for f in selected}) != 1:
            return _unavailable("The calculation needs compatible inputs from the same statement and currency.")
        if formula == "roe" and len({f["file"] for f in selected}) != 1:
            return _unavailable("Return on equity needs net income and equity from the same filing.")
        pairs = {(f["metric"], f["year"]): f for f in selected}
        if formula == "free_cash_flow":
            year = years[-1]
            cash = pairs[("operating_cash_flow", year)]
            capex = pairs[("capital_expenditure", year)]
            top, outflow = Decimal(cash["value"]), abs(Decimal(capex["value"]))
            with localcontext() as context:
                context.prec = 28
                result = top - outflow
            expression = "operating_cash_flow - abs(capital_expenditure)"
            amount = _money(result, cash["currency"])
            if abs(result) >= SCALES["billions"]:
                amount += f" ({_money(result, cash['currency'], 'billions')})"
            lines.append(
                f"**Free cash flow (fiscal {year}): {amount}** [{cash['source_id']}]\n\n"
                f"{expression.replace('_', ' ')} = "
                f"{_money(top, cash['currency'])} − {_money(outflow, capex['currency'])}."
            )
            verification["calculations"].append({
                "metric": formula, "year": year, "formula": expression,
                "inputs": [cash, capex], "result": str(result), "unit": cash["currency"],
            })
        elif formula == "current_ratio":
            year = years[-1]
            assets = pairs[("current_assets", year)]
            liabilities = pairs[("current_liabilities", year)]
            top, bottom = Decimal(assets["value"]), Decimal(liabilities["value"])
            if bottom <= 0:
                return _unavailable("The calculation requires a positive denominator; the reported value is zero or negative.")
            with localcontext() as context:
                context.prec = 28
                result = top / bottom
            expression = "current_assets / current_liabilities"
            lines.append(
                f"**Current ratio (fiscal {year}): {result:.2f}×** [{assets['source_id']}]\n\n"
                f"{expression.replace('_', ' ')} = "
                f"{_money(top, assets['currency'])} ÷ {_money(bottom, liabilities['currency'])}."
            )
            verification["calculations"].append({
                "metric": formula, "year": year, "formula": expression,
                "inputs": [assets, liabilities], "result": str(result),
                "unit": "ratio", "display_decimals": 2,
            })
        elif formula == "metric_growth":
            metric = metrics[0]
            current, prior = pairs[(metric, years[-1])], pairs[(metric, years[0])]
            top, bottom = Decimal(current["value"]), Decimal(prior["value"])
            if bottom == 0:
                return _unavailable("The calculation requires a non-zero prior-year denominator; the reported value is zero.")
            with localcontext() as context:
                context.prec = 28
                result = (top - bottom) / bottom * 100
            expression = f"(current_{metric} - prior_{metric}) / prior_{metric} * 100"
            title = f"{LABELS[metric]} growth"
            lines.append(
                f"**{title} (fiscal {years[0]} to {years[-1]}): {result:.2f}%** [{current['source_id']}]\n\n"
                f"{expression.replace('_', ' ')} = "
                f"({_money(top, current['currency'])} − {_money(bottom, prior['currency'])}) ÷ "
                f"{_money(bottom, prior['currency'])} × 100."
            )
            verification["calculations"].append({
                "metric": formula, "year": years[-1], "formula": expression,
                "inputs": [current, prior], "result": str(result),
                "unit": "percent", "display_decimals": 2,
            })
        else:
            periods = years if formula in ("operating_margin", "net_margin", "roe") else [years[-1]]
            for year in periods:
                if formula == "operating_margin":
                    numerator, denominator = pairs[("operating_income", year)], pairs[("revenue", year)]
                    expression = "operating_income / revenue * 100"
                    title = "Operating margin"
                elif formula == "net_margin":
                    numerator, denominator = pairs[("net_income", year)], pairs[("revenue", year)]
                    expression = "net_income / revenue * 100"
                    title = "Net margin"
                else:
                    numerator, denominator = pairs[("net_income", year)], pairs[("shareholders_equity", year)]
                    expression = "net_income / shareholders_equity * 100"
                    title = "Return on equity"
                top, bottom = Decimal(numerator["value"]), Decimal(denominator["value"])
                if bottom <= 0:
                    return _unavailable("The calculation requires a positive denominator; the reported value is zero or negative.")
                with localcontext() as context:
                    context.prec = 28
                    result = (top / bottom) * 100
                citations = numerator["source_id"]
                if denominator["source_id"] != numerator["source_id"]:
                    citations = f"{numerator['source_id']}, {denominator['source_id']}"
                lines.append(
                    f"**{title} (fiscal {year}): {result:.2f}%** [{citations}]\n\n"
                    f"{expression.replace('_', ' ')} = "
                    f"{_money(top, numerator['currency'])} ÷ {_money(bottom, denominator['currency'])} × 100."
                )
                verification["calculations"].append({
                    "metric": formula, "year": year, "formula": expression,
                    "inputs": [numerator, denominator], "result": str(result),
                    "unit": "percent", "display_decimals": 2,
                })
    else:
        for fact in selected:
            value = Decimal(fact["value"])
            outflow = fact["metric"] == "capital_expenditure"
            shown = abs(value) if outflow else value
            amount = _money(shown, fact["currency"])
            if abs(shown) >= SCALES["billions"]:
                amount += f" ({_money(shown, fact['currency'], 'billions')})"
            when = {"year_end": "at fiscal year end", "as_of": "reported balance in", "annual": "fiscal"}[fact["period_kind"]]
            lines.append(f"**{LABELS[fact['metric']]} ({when} {fact['year']}): {amount}**" +
                         (" cash outflow magnitude" if outflow else "") + f" [{fact['source_id']}]")
            if outflow:
                verification["calculations"].append({"metric": "capital_expenditure_magnitude", "formula": "abs(reported_cash_flow)", "inputs": [fact], "result": str(shown), "unit": fact["currency"]})
    return {"text": "\n\n".join(lines), "warnings": [], "verification": verification}
