"""Independent synthetic adversarial cases for source-linked financial figures.

All companies, statement rows, amounts and dates below are synthetic test data.
These are safety-contract tests, not transcriptions from the development filing
benchmark and not evidence of accuracy on arbitrary PDF layouts.
"""

from decimal import Decimal
import unittest

from numeric_evidence import quantitative_answer, table_facts


def source(rows, *, source_id="S1", units="USD millions", years="2025 2024",
           statement="CONSOLIDATED STATEMENTS OF OPERATIONS", currency=None):
    value = {
        "id": source_id,
        "file": "Synthetic Company annual financial statements.pdf",
        "page": 8,
        "page_label": "6",
        "text": f"Synthetic Company\n{statement}\n({units})\nYears ended\n{years}\n{rows}",
    }
    if currency is not None:
        value["currency"] = currency
    return value


def selected(facts, metric, year):
    return [f for f in facts if f["metric"] == metric and f["year"] == year]


class NumericEvidenceSafety(unittest.TestCase):
    def assert_not_verified(self, answer):
        """Both an out-of-scope route and an explicit abstention are safe."""
        if answer is not None:
            self.assertIn(answer["verification"]["status"], ("unavailable", "not_checked"))

    def assert_fact_value(self, facts, metric, year, expected):
        matches = selected(facts, metric, year)
        self.assertTrue(matches, (metric, year, facts))
        self.assertTrue(all(Decimal(f["value"]) == Decimal(expected) for f in matches), matches)
        return matches

    def test_base_units_are_bound_to_row_year_and_explicit_currency(self):
        evidence = source("Total net sales 240 200\nOperating income 48 30\nNet income 33 25")
        facts = table_facts([evidence])
        matches = self.assert_fact_value(facts, "revenue", 2025, "240000000")
        self.assert_fact_value(facts, "revenue", 2024, "200000000")
        self.assert_fact_value(facts, "operating_income", 2025, "48000000")
        for fact in matches:
            self.assertEqual(fact["currency"], "USD")
            self.assertEqual(fact["source_id"], "S1")
            self.assertIn("Total net sales", fact["row"])
            self.assertTrue(fact["header"])
            self.assertIn("scale", fact)

    def test_reversed_year_columns_preserve_their_actual_order(self):
        facts = table_facts([source("Total net sales 200 240", years="2024 2025")])
        self.assert_fact_value(facts, "revenue", 2025, "240000000")
        self.assert_fact_value(facts, "revenue", 2024, "200000000")

    def test_decimal_reported_amounts_preserve_exact_base_units(self):
        facts = table_facts([source("Total net sales 240.125 200.375")])
        self.assert_fact_value(facts, "revenue", 2025, "240125000")
        self.assert_fact_value(facts, "revenue", 2024, "200375000")

    def test_split_date_headers_do_not_become_extra_numeric_columns(self):
        evidence = source("Total net sales 240 200", years="December 31,\n2025\nDecember 31,\n2024")
        facts = table_facts([evidence])
        self.assert_fact_value(facts, "revenue", 2025, "240000000")
        self.assert_fact_value(facts, "revenue", 2024, "200000000")

    def test_an_unrelated_row_with_same_amount_cannot_replace_revenue(self):
        evidence = source("Total net sales 80 70\nOperating income 20 18\nNet income 240 200")
        facts = table_facts([evidence])
        self.assert_fact_value(facts, "revenue", 2025, "80000000")
        answer = quantitative_answer("What was total net sales in fiscal 2025? Give the amount in USD millions.", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assert_fact_value(answer["verification"]["facts"], "revenue", 2025, "80000000")

    def test_total_liabilities_is_not_total_liabilities_and_equity(self):
        evidence = source(
            "Total liabilities 150 125\nTotal shareholders' equity 90 75\n"
            "Total liabilities and shareholders' equity 240 200",
            statement="CONSOLIDATED BALANCE SHEETS",
        )
        facts = table_facts([evidence])
        self.assert_fact_value(facts, "total_liabilities", 2025, "150000000")
        self.assertFalse(any(f["metric"] == "total_liabilities" and Decimal(f["value"]) == Decimal("240000000") for f in facts))

    def test_parenthesized_outflow_keeps_sign_and_scale(self):
        evidence = source(
            "Cash generated by operating activities 80 70\n"
            "Payments for acquisition of property, plant and equipment (2,450) (1,900)",
            statement="CONSOLIDATED STATEMENTS OF CASH FLOWS",
        )
        facts = table_facts([evidence])
        self.assert_fact_value(facts, "capital_expenditure", 2025, "-2450000000")
        answer = quantitative_answer(
            "What were payments for acquisition of property, plant and equipment "
            "(outflow magnitude) in fiscal 2025? Give the amount in USD millions.", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assertNotIn("$2.45 million", answer["text"])
        self.assert_fact_value(answer["verification"]["facts"], "capital_expenditure", 2025, "-2450000000")

    def test_requested_year_absent_from_table_is_unavailable(self):
        self.assert_not_verified(quantitative_answer(
            "What was total net sales in fiscal 2023?", [source("Total net sales 240 200")]))

    def test_missing_requested_row_does_not_borrow_a_neighbor(self):
        self.assert_not_verified(quantitative_answer(
            "What was total net sales in fiscal 2025?", [source("Net income 240 200")]))

    def test_conflicting_same_metric_year_sources_cannot_verify(self):
        sources = [source("Total net sales 240 200"), source("Total net sales 241 200", source_id="S2")]
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025?", sources))

    def test_same_source_conflicting_repeated_row_cannot_verify(self):
        evidence = source("Total net sales 240 200\nTotal net sales 241 200")
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025?", [evidence]))

    def test_dollar_symbol_does_not_establish_usd_currency(self):
        evidence = source("Total net sales $ 240 $ 200", units="In millions")
        self.assertFalse(any(f.get("currency") == "USD" for f in table_facts([evidence])))
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025 in USD?", [evidence]))

    def test_missing_scale_does_not_assume_millions(self):
        evidence = source("Total net sales 240 200", units="USD")
        facts = selected(table_facts([evidence]), "revenue", 2025)
        # A parser may reject this layout or support explicitly unscaled dollars.
        self.assertTrue(all(Decimal(f["value"]) == Decimal("240") for f in facts), facts)
        answer = quantitative_answer("What was total net sales in fiscal 2025 in USD millions?", [evidence])
        if answer is not None and answer["verification"]["status"] == "verified":
            self.assert_fact_value(answer["verification"]["facts"], "revenue", 2025, "240")

    def test_missing_year_header_does_not_use_year_in_question(self):
        evidence = source("Total net sales 240 200", years="")
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025?", [evidence]))

    def test_dashes_are_missing_cells_not_zero_or_shifted_columns(self):
        evidence = source("Total net sales — 200\nOperating income 20 18")
        self.assertFalse(selected(table_facts([evidence]), "revenue", 2025))
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025?", [evidence]))

    def test_truncated_row_does_not_guess_the_missing_column(self):
        evidence = source("Total net sales 240")
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2024?", [evidence]))

    def test_per_share_exception_does_not_scale_earnings_per_share(self):
        evidence = source("Total net sales 240 200\nBasic earnings per share 2.40 2.00", units="USD millions, except per share amounts")
        self.assertFalse(any("per_share" in f["metric"] for f in table_facts([evidence])))
        self.assert_not_verified(quantitative_answer("What were basic earnings per share in fiscal 2025?", [evidence]))

    def test_second_table_cannot_inherit_first_table_scale(self):
        evidence = source("Total net sales 240 200")
        evidence["text"] += "\nCONSOLIDATED STATEMENTS OF CASH FLOWS\n(USD thousands)\nYears ended\n2025 2024\nCash generated by operating activities 80 70"
        cash_flow = selected(table_facts([evidence]), "operating_cash_flow", 2025)
        # Supporting the second table is optional; attributing millions to it is not.
        self.assertTrue(all(Decimal(f["value"]) == Decimal("80000") for f in cash_flow), cash_flow)

    def test_explicit_foreign_currency_cannot_be_overridden_by_source_metadata(self):
        evidence = source("Total net sales 240 200", units="EUR millions", currency="USD")
        facts = table_facts([evidence])
        self.assertFalse(any(f.get("currency") == "USD" for f in facts), facts)
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025 in USD?", [evidence]))

    def test_quarterly_table_is_not_annual_evidence(self):
        evidence = source("Total net sales 240 200")
        evidence["text"] = evidence["text"].replace("Years ended", "Three months ended")
        self.assert_not_verified(quantitative_answer("What was total net sales in fiscal 2025?", [evidence]))

    def test_operating_margin_does_not_divide_by_zero(self):
        evidence = source("Total net sales 0 200\nOperating income 10 30")
        self.assert_not_verified(quantitative_answer("What was operating margin in fiscal 2025?", [evidence]))

    def test_revenue_growth_does_not_divide_by_zero(self):
        evidence = source("Total net sales 240 0")
        self.assert_not_verified(quantitative_answer("What was revenue growth from fiscal 2024 to fiscal 2025?", [evidence]))

    def test_unsupported_growth_scopes_never_receive_verification(self):
        evidence = source("Total net sales 240 200\nOperating income 48 30")
        questions = [
            "What was constant currency revenue growth from fiscal 2024 to fiscal 2025?",
            "What was organic revenue growth from fiscal 2024 to fiscal 2025?",
            "What was Europe's revenue growth from fiscal 2024 to fiscal 2025?",
            "What was quarterly revenue growth in fiscal 2025?",
            "Forecast revenue growth for fiscal 2026.",
        ]
        for question in questions:
            with self.subTest(question=question):
                self.assert_not_verified(quantitative_answer(question, [evidence]))

    def test_a_why_question_is_not_fully_answered_by_a_reported_number(self):
        self.assert_not_verified(quantitative_answer(
            "Why did revenue rise in fiscal 2025?", [source("Total net sales 240 200")]))

    def test_a_named_company_cannot_use_another_companys_equal_valued_row(self):
        alpha = source("Total net sales 240 200")
        alpha.update(file="Synthetic Alpha annual report.pdf", entity_names=["Alpha"])
        beta = source("Total net sales 240 200", source_id="S2")
        beta.update(file="Synthetic Beta annual report.pdf", entity_names=["Beta"])
        answer = quantitative_answer("What was Beta revenue in fiscal 2025?", [alpha, beta])
        if answer is not None and answer["verification"]["status"] == "verified":
            # Either abstain or explicitly bind the named entity to its source.
            self.assertTrue(answer["verification"]["facts"])
            self.assertTrue(all(f["source_id"] == "S2" for f in answer["verification"]["facts"]))

    def test_a_later_quarterly_table_cannot_inherit_annual_header(self):
        evidence = source(
            "Total net sales 240 200\nQuarterly supplemental information\n"
            "Three months ended\n2025 2024\nOperating income 18 15")
        self.assert_not_verified(quantitative_answer("What was operating income in fiscal 2025?", [evidence]))

    def test_interim_balance_dates_cannot_be_certified_as_fiscal_year_end(self):
        evidence = source("Total assets 240 200", statement="CONSOLIDATED BALANCE SHEETS",
                          years="September 30,\n2025\nDecember 31,\n2024")
        evidence["text"] = evidence["text"].replace("Years ended\n", "")
        self.assert_not_verified(quantitative_answer("What were total assets at fiscal year end 2025?", [evidence]))

    def test_an_additional_expenses_request_cannot_silently_disappear(self):
        self.assert_not_verified(quantitative_answer(
            "What were revenue and expenses in fiscal 2025?", [source("Total net sales 240 200")]))

    def test_an_as_of_constraint_is_not_a_request_for_two_fiscal_years(self):
        self.assert_not_verified(quantitative_answer(
            "What was revenue in fiscal 2025 as of 2024?", [source("Total net sales 240 200")]))

    def test_a_segment_section_cannot_supply_a_consolidated_row(self):
        evidence = source("Total net sales 240 200\nSegment information:\nEurope:\nOperating income 18 15")
        self.assert_not_verified(quantitative_answer("What was operating income in fiscal 2025?", [evidence]))

    def test_projected_or_pro_forma_headers_are_not_reported_annual_figures(self):
        for qualifier in ("Forecast", "Pro forma", "Adjusted non-GAAP"):
            with self.subTest(qualifier=qualifier):
                evidence = source("Total net sales 240 200")
                evidence["text"] = evidence["text"].replace("Years ended\n", qualifier + "\nYears ended\n")
                self.assert_not_verified(quantitative_answer("What was reported revenue in fiscal 2025?", [evidence]))

    def test_conflicting_row_currency_symbols_cannot_be_silently_discarded(self):
        for row in ("Total net sales € 240 € 200", "Total net sales £ 240 £ 200",
                    "Total net sales $ 240 € 200"):
            with self.subTest(row=row):
                self.assert_not_verified(quantitative_answer(
                    "What was revenue in fiscal 2025 in USD millions?", [source(row)]))

    def test_net_cash_from_operations_alias_does_not_claim_investing_cash(self):
        evidence = source(
            "Net cash from operations 136,162 118,548\n"
            "Net cash used in investing activities (45,000) (30,000)",
            statement="CONSOLIDATED STATEMENTS OF CASH FLOWS",
        )
        answer = quantitative_answer("What was net cash from operations in fiscal 2025?", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assert_fact_value(answer["verification"]["facts"], "operating_cash_flow", 2025, "136162000000")
        self.assertNotIn("45,000", answer["text"])

    def test_microsoft_style_income_statements_heading_is_supported(self):
        evidence = source(
            "Total revenue 281,724 245,122\nOperating income 128,528 109,204",
            statement="Financial Statements: Income Statements",
        )
        facts = table_facts([evidence])
        self.assert_fact_value(facts, "revenue", 2025, "281724000000")
        answer = quantitative_answer("What was total revenue in fiscal 2025?", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")

    def test_bare_income_statements_heading_is_recognized(self):
        evidence = source("Total revenue 281,724 245,122", statement="Income Statements")
        self.assert_fact_value(table_facts([evidence]), "revenue", 2025, "281724000000")

    def test_segment_income_statements_heading_remains_unsupported(self):
        evidence = source(
            "Total revenue 281,724 245,122\nOperating income 128,528 109,204",
            statement="Segment Income Statements",
        )
        self.assertFalse(table_facts([evidence]))
        self.assert_not_verified(quantitative_answer(
            "What was total revenue in fiscal 2025?", [evidence]))

    def test_free_cash_flow_uses_operating_cash_minus_capex_magnitude(self):
        evidence = source(
            "Cash generated by operating activities 111,482 118,254\n"
            "Payments for acquisition of property, plant and equipment (12,715) (9,447)",
            statement="CONSOLIDATED STATEMENTS OF CASH FLOWS",
        )
        answer = quantitative_answer("What was free cash flow in fiscal 2025?", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assertIn("$98,767 million", answer["text"])
        self.assertEqual(answer["verification"]["calculations"][0]["formula"],
                         "operating_cash_flow - abs(capital_expenditure)")
        self.assertEqual(answer["verification"]["calculations"][0]["result"], "98767000000")

    def test_free_cash_flow_does_not_invent_missing_capex(self):
        evidence = source(
            "Cash generated by operating activities 111,482 118,254",
            statement="CONSOLIDATED STATEMENTS OF CASH FLOWS",
        )
        self.assert_not_verified(quantitative_answer(
            "What was free cash flow in fiscal 2025?", [evidence]))

    def test_net_margin_uses_net_income_over_revenue(self):
        evidence = source("Total net sales 416,161 391,035\nNet income 112,010 93,736")
        answer = quantitative_answer("What was net margin in fiscal 2025?", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assertIn("26.92%", answer["text"])
        self.assertEqual(answer["verification"]["calculations"][0]["formula"],
                         "net_income / revenue * 100")

    def test_return_on_equity_joins_income_and_year_end_equity(self):
        income = source("Total net sales 416,161 391,035\nNet income 112,010 93,736")
        balance = source(
            "Total shareholders' equity 73,733 56,950",
            statement="CONSOLIDATED BALANCE SHEETS",
            years="September 27,\n2025\nSeptember 28,\n2024",
            source_id="S2",
        )
        balance["text"] = balance["text"].replace("Years ended\n", "Years ended\n")
        balance["fiscal_year_ends"] = {"2025": "September 27, 2025", "2024": "September 28, 2024"}
        answer = quantitative_answer("What was return on equity in fiscal 2025?", [income, balance])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assertIn("151.91%", answer["text"])
        self.assertEqual(answer["verification"]["calculations"][0]["formula"],
                         "net_income / shareholders_equity * 100")

    def test_metric_growth_works_for_operating_income(self):
        evidence = source("Operating income 133,050 123,216\nTotal net sales 416,161 391,035")
        answer = quantitative_answer(
            "What was operating income growth from fiscal 2024 to fiscal 2025?", [evidence])
        self.assertIsNotNone(answer)
        self.assertEqual(answer["verification"]["status"], "verified")
        self.assertIn("7.98%", answer["text"])

    def test_adjusted_free_cash_flow_is_not_verified(self):
        evidence = source(
            "Cash generated by operating activities 111,482 118,254\n"
            "Payments for acquisition of property, plant and equipment (12,715) (9,447)",
            statement="CONSOLIDATED STATEMENTS OF CASH FLOWS",
        )
        self.assert_not_verified(quantitative_answer(
            "What was adjusted free cash flow in fiscal 2025?", [evidence]))


if __name__ == "__main__":
    unittest.main()
